### ISSUE TITLE
remove `*.sublime-keymap` 

### ISSUE THREAD

**Issue by aziz** [inkless/lebab-sublime#1]
All of them are empty

```
[
  {
    "keys": [],
    "command": "lebab"
  }
]
```

and Sublime is complaining about it:

`Unable to parse binding {command: lebab, keys: []}`

**Comment by inkless** [comment]
@aziz  What's your sublime's version and what's the OS (linux/windows/Mac OS X)?
I haven't seen this issue before, can you  try add a user specific key bindings to see if it might solve the problem?
For example, if you are using Mac OS X:
Click Preferences -> Package Settings ->  Lebab -> Key Bindings - User
And paste this to it:

```
[
  {
    "keys": ["super+shift+l"],
    "command": "lebab"
  }
]
```

**Comment by aziz** [comment]
Yes defining a custom key binding will fix this issue, but my point is that having those empty files are just redundant. There's no use for them and you're adding an error in my console log.
I don't want a custom key binding, I'm just happy with the command I get in the command palette

**Comment by inkless** [comment]
I c what you are saying. I used to have a key binding and removed it a little bit later. Sure, I can remove it. Thanks for you suggestion. I'll let you know when it's updated.

**Comment by inkless** [comment]
@aziz Just updated the plugin, you should be able to see the updates in your sublime.
