### ISSUE TITLE
A setting to pass options to `lebab`

### ISSUE THREAD

**Issue by aziz** [inkless/lebab-sublime#3]
It's essential to be able to pass arguments to lebab. Things like `--disable commonjs` that people are talking about [here](https://github.com/mohebifar/lebab/issues/155)

**Comment by inkless** [comment]
Just added support to disable commonjs

Add following settings to your default/user settings:

``` json
{
  "commonjs": false
}
```

This will disable import and export conversion.

**Comment by aziz** [comment]
This is not enough! 
You need to cover all the other options as well to allow the plugin users to disable or enable them through the settings. 

I suggest not hard-coding any of these options but just provide two `disable` and `enable` options so that anyone can pass an array transforms. 

```
  Safe transforms:

    + arrow .......... callback to arrow function
    + let ............ var to let/const
    + arg-spread ..... use of apply() to spread operator
    + obj-method ..... function values in objects to methods
    + obj-shorthand .. {foo: foo} to {foo}
    + no-strict ...... remove "use strict" directives
    + commonjs ....... CommonJS module loading to import/export

  Unsafe transforms:

    + class .......... prototype assignments to class declaration
    + template ....... string concatenation to template string
    + default-param .. use of || to default parameters
```
