### ISSUE TITLE
Lebab 2.0 to break compatibility

### ISSUE THREAD

**Issue by nene** [inkless/lebab-sublime#4]
Just giving a small heads-up as I'm planning to release Lebab 2.0 which has changed the command line API.

The crucial change is that transforms are no more enabled by default. One needs to specify them explicitly using the new `--transform` option.

This means the simple configuration as implemented in #3 won't really suffice.

Also I'd advise against enabling all the transforms by default. Some of them are fairly safe to apply, while others are somewhat unsafe and should be applied with care, and yet others do syntax changes beyond ES6 (like the new ES7 exponent).

For details see: https://github.com/mohebifar/lebab/tree/lebab-2.0

**Comment by inkless** [comment]
@nene  Thanks to @aziz , this is fixed.
