### ISSUE TITLE
Default list of transforms is a bit problematic

### ISSUE THREAD

**Issue by nene** [inkless/lebab-sublime#6]
While I think it's good to enable just the safe transforms, two entries are problematic:
- `for-of` only works with for loops that use `let` so it really has `let` transform as a pre-requisite, but the latter is currently not categorized as safe because of some bugs.
- `multi-var` is just an opinionated refactoring and not about ES5->ES6 at all.

**Comment by aziz** [comment]
Thanks @nene for your valuable feedback. I addressed the issue and remove those two transforms in 0.0.7
